### ISSUE TITLE
Bad Gateway error

### ISSUE THREAD

**Issue by mhdshb** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#1]
# Module: 8
#### Step: 10

Description of issue
 After adding the instance I am getting a Bad Gateway error.

![image](https://user-images.githubusercontent.com/7451627/92913164-3224bf80-f433-11ea-90fe-9bd9d49eedf2.png)

Repro steps:
Same steps that are made in the Demo lab.

**Comment by janeteblake** [comment]
mhdshb, usually this type of error means it did not like the URL. Were you able to select that URL from a drop-down?
