### ISSUE TITLE
Proposed fixes for Lab 5 Exercise 4 Instructions multiple tasks. 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#12]
# Lab/Demo: 05
#### Step: 05

Description of issue

Recommend adding the **types** of fields that should be created ie: Int64 or string, etc. ie: (of type Int64)

Repro steps:
https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/blob/master/Instructions/Labs/Lab%205%20-%20Code%20Extension%20%26%20Development.md#task-2-create-a-table-mlaairportmileschart
______________________________________________________________________________________________________________________________________

# Lab/Demo: 05
#### Step: 05

Description of issue

Add clarifying text that the **DDTCustFlyDetails.MyLabAirlines** table can be found under **Table Extensions**. 

Repro steps:
https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/blob/master/Instructions/Labs/Lab%205%20-%20Code%20Extension%20%26%20Development.md#task-13-table-ddtcustflydetails--modifiedfield-method

**Comment by janeteblake** [comment]
Good feedback; incorporated; thank you.
