### ISSUE TITLE
Lab 6a Proposed changes

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#13]
# Lab/Demo: 6a
#### Step: 02

Description of issue
Add clarifying text that the **MyLabAirlines** project, otherwise just selecting **Add New > Item** from the overall Solution doesn't give the D365 options incl Data Model

Repro steps:
https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/blob/master/Instructions/Labs/Lab%206a%20-%20Data%20Export%20Import%20using%20Data%20Entity.md#exercise-1-create-new-entity-for-import

**Comment by janeteblake** [comment]
This is done, thank you very much for the input!
