### ISSUE TITLE
Internet Explorer will no longer be supported in Azure on March 31, 2021

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#14]
# Lab/Demo: 6b
## Lab Environment

Description of issue
**Effective March 31, 2021 Azure will no longer support IE**. It is suggested to use **MS Edge** on these labs. 
![2021-02-22_161650](https://user-images.githubusercontent.com/62302805/108771581-e4f06200-7529-11eb-9f29-cc68668f198c.JPG)

Repro steps:
https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/blob/master/Instructions/Labs/Lab%206b%20-%20Recurring%20Data%20Transfer.md#lab-environment

**Comment by janeteblake** [comment]
Thank you for this very important information. We are researching now.

**Comment by janeteblake** [comment]
I am told that "we cannot add Edge to this VM as Edge is not supported on Windows Server Datacenter, which is what this [the hosted] VM uses." So we will need to remove all or part of labs 6b, 8a, and 8b by the end of March. We are working on an update to be released next quarter and will ensure that the portal is not referenced there. Again, thank you for the alert!
