### ISSUE TITLE
Lab 8b Exercise 2 Task 2 Step 4. Versioning is not available. 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#16]
# Lab/Demo: 8b
#### Step: 04

Description of issue

**v11.0.1** of the **Newtonsoft.Json** was **no longer available** for selection. Since the instructions say it is important to use this version 11.0.1, the lab user will hit a **blocking issue.** Same for **ServiceBus**.

Repro steps:
https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/blob/master/Instructions/Labs/Lab%208b%20-%20Logic%20App%20Integration.md#task-2-create-a-c-class-to-populate-message-in-service-bus

**Comment by hope77777** [comment]
![image](https://user-images.githubusercontent.com/62302805/108785338-37884900-753f-11eb-878a-2323562eba43.png)

**Comment by hope77777** [comment]
![image](https://user-images.githubusercontent.com/62302805/108785384-4cfd7300-753f-11eb-80e7-095530de1b42.png)

**Comment by janeteblake** [comment]
Hi, and thanks for your comments. In the ALH VM that I tested in, both of those versions were available in the version dropdown toward the right. Please let us know that you can see them!
![image](https://user-images.githubusercontent.com/54034556/111190070-1d191c80-858d-11eb-8bdc-23d7c6071907.png)
![image](https://user-images.githubusercontent.com/54034556/111190092-230efd80-858d-11eb-94a1-686556aec9cf.png)

**Comment by janeteblake** [comment]
Hi, closing this. Let me know if still an issue for you.
