### ISSUE TITLE
Lab 8c Recommendations

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#17]
# Lab/Demo: 8c
#### Steps: 11

Description of issue
Recommend adding text to suggest that the student saves before building 

Repro steps:
https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/blob/master/Instructions/Labs/Lab%208c%20-%20Calling%20External%20Web%20Service.md#task-1-creating-the-c-wrapper-class

https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/blob/master/Instructions/Labs/Lab%208c%20-%20Calling%20External%20Web%20Service.md#task-2-creating-the-d365-for-fin--ops-class

**Comment by janeteblake** [comment]
This is done, thank you very much for the input!
