### ISSUE TITLE
Lab XX Exercise 2 Task 1 Step 3 Automated Cloud Flow. 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#18]
# Lab/Demo: xx
#### Step: 03

Description of issue
**Automated flow** is now called **Automated Cloud Flow**. **Screenshot would also need to be updated.** 

Repro steps:
https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/blob/master/Instructions/Labs/Lab%20xx%20-%20Business%20Events.md#task-1-launch-microsoft-flow

**Comment by janeteblake** [comment]
Thank you for your input! We have made these changes - please re-open if the changes do not flow all the way through.
