### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by Tattedgeek** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#24]
# Module: 4
#### Step: 00

Description of issue
When doing a build, it fails due to not being able to stop AXBatchService
Repro steps:

![image](https://user-images.githubusercontent.com/31896372/174491295-6f75fc59-87eb-4841-b8d9-0f732ad8c752.png)

Solution:

Need to manually kill the service in the Command Prompt and then the build will succeed.

**Comment by janeteblake** [comment]
Thank you for reporting 24-30! We will take a look.

**Comment by janeteblake** [comment]
You mean task 11, right? I could not replicate, see screenshot. If it keeps happening, though, the lab hoster should add resources to the VMs. 
![image](https://user-images.githubusercontent.com/54034556/196825609-2b6ae073-857c-4183-955f-f1538648c29a.png)
