### ISSUE TITLE
System timeout

### ISSUE THREAD

**Issue by Tattedgeek** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#25]
# Module: 3
#### Step: 00

Description of issue
Debugging fails

Repro steps:
![image](https://user-images.githubusercontent.com/31896372/174491340-6c5386b4-802c-46fc-80fc-9209fe5b9184.png)

Have to re-run the debugging a second time and it works.

**Comment by janeteblake** [comment]
Please provide repro steps. I am at https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/blob/master/Instructions/Labs/MB500_M3E1.md (module 3 exercise 1) and there is no debugging requested. Closing for now.
