### ISSUE TITLE
Issues when doing lab review

### ISSUE THREAD

**Issue by Tattedgeek** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#27]
# Module: 5
### Task: Pre-reqs

Description of issue
There is a compile error with 24 errors when using the pre-built project for Data Model. (see screen shots)

![image](https://user-images.githubusercontent.com/31896372/175785157-9d7eb010-8a48-484e-9b4b-db5e65e00346.png)

After review, I discovered There is a missing reference in the MBTInsurancePremium table/InsurancePremium field group (AssetInsuranceId). This is causing a compile error. 

There is a missing label reference in MBTInsurancePremium table/InsurancePremium field group (AssetInsuranceId). This is causing a compile error. 

I fixed those issues, and still get many compile errors. 

![image](https://user-images.githubusercontent.com/31896372/175785193-7d8c62e9-337d-4073-9021-e9315d721711.png)

I re-did the exercise to create the Data Model and so far it's working without any error.

Repro steps:

1.
1.
1.

**Comment by janeteblake** [comment]
Could you please clarify which exercise in lab 5 this is?

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this is no longer an issue.

**Comment by janeteblake** [comment]
Thank you.
