### ISSUE TITLE
Project UI Labs different

### ISSUE THREAD

**Issue by Tattedgeek** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#29]
# Module: 4
#### Step: 00

Description of issue
The lab exercises have you create one extended database, but the pre-req lab file has two extended databases listed. The guide and file don't match, and they still get compile errors.

Repro steps:

1.
1.
1.

**Comment by janeteblake** [comment]
Could you please clarify which exercise and task. Thank you.

**Comment by Tattedgeek** [comment]
It would be Lab 04, Exercise 1, Task #11

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this is no longer an issue.

**Comment by janeteblake** [comment]
Thank you
