### ISSUE TITLE
LCS Lifecycle Services 

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#3]
Lab 1 https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/blob/master/Instructions/Labs/Lab%201%20-%20Development%20Environment%20configuration.md

The instructions advise LCS is optional but first steps call for lifecycle services to be leveraged.  LCS comes up again in the lab in Lab 8b - Logic App Integration.

In other Dynamics titles (MB-300 comes to mind) these sections have been removed.  Are there plans to remove these sections and update the directions or advise how an LCS environment can be provisioned?  

thank you for your time.

**Comment by janeteblake** [comment]
Thanks for the feedback! We removed LCS from the functional courses, as you noted, and the developer course is next on our list. Since the developer course is being updated, we will remove and not revise. 

We appreciate your feedback and will be taking action shortly on this!

**Comment by mreherefortea** [comment]
Thanks Janet!

**Comment by janeteblake** [comment]
I haven't forgotten this. I'm combining this with several other Developer updates to be released shortly. Thanks for your patience!
Janet

**Comment by janeteblake** [comment]
Hi there, the update is going out tonight!
