### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by Tattedgeek** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#30]
File MB500TrainingProjectCode.axpp in the code is called MB500TrainingProjectCoding.

I think the names should match to prevent confusion.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this is no longer an issue.

**Comment by janeteblake** [comment]
Thank you
