### ISSUE TITLE
Labs are out of order

### ISSUE THREAD

**Issue by Tattedgeek** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#57]
# Module: 10
## Lab/Demo: 01

Description of issue:
This lab is to create the data management. It is currently listed as module 10, but in the new revision of the course, data management is now covered in Module 6. This is mostly noticed when you try to do the labs without loading the pre-configured modules in each lab.

I will make a note during my next lab review.

Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by janeteblake** [comment]
Corrected, thank you
