### ISSUE TITLE
Module 06: Data migration confusion about module placement.

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#68]
# Module: 10

Description of issue

On 28 Nov 2022 Module 10 was changed to Module 6 Exercise 1. However, there is already an existing Module 6 with Exercise 1.

Looking at the content this new module 6 should be module 6 exercise 2, can this be updated in order to avoid confusion?

![image](https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/assets/98971092/a3e8637c-d689-4c79-ad3b-d60fde2e3f17)

![image](https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/assets/98971092/1d126808-55d5-4b03-9ef0-aa9f6619ea48)

**Comment by janeteblake** [comment]
Thank you very much, Kiyani1, for raising the issue! We appreciate the heads-up. 

We just merged a fix, please let us know if your concern is addressed.
