### ISSUE TITLE
Module 10: Data migration confusion about module placement.

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#70]
# Module: 10
### Task: 01

Description of issue

Hello,

Please update Module 10 to Module 6 Exercise 2 as that module is the pre-requisite for Module 7. Please see the screenshots below which state **MB500TrainingProjectExtension** is the pre-requisite for Module 7, which is currently being created in Module 10.

Could you resolve this issue on the highest priority?

![image](https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/assets/98971092/2c0de038-b6c1-4dba-b80c-8fb281ed574e)

![image](https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/assets/98971092/8d1b4274-765a-4312-9ae1-7a8e04b01422)

**Comment by janeteblake** [comment]
Kiyani1, we are looking into clarifying your issues. Thank you.

**Comment by janeteblake** [comment]
Kiyani1, can you please verify if you did or did not follow the order in the Trainer Prep Guide in the Learning Download Center https://learningdownloadcenter.microsoft.com/ ?

**Comment by Kiyani1** [comment]
I verified from the Prep guide that after module 6 we are supposed to perform module 10.  This issue was pointed out to us by one of the instructors looking at the structure of MD files I was not able to find any hint or reference that module 10 specifically should be after module 6.

Can this Module be updated to Module 6 Exercise 2 or placed after Module 6 Exercise 1? Looking at the repository we placed it after module 9 as it appeared to be the next module.

**Comment by janeteblake** [comment]
Thank you for your response. We will be updating the trainer materials to correct this. In the meantime, a workaround would be to point the learners to the correct lab at https://microsoftlearning.github.io/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/, rather than using Skillable's instructions, which force the sequence.

**Comment by janeteblake** [comment]
We've updated the labs, and scheduled a corresponding update of the trainer materials. Thank you for bringing this to our attention! Please keep in mind that prerequisites are EITHER performing the lab or importing the supporting material.
