### ISSUE TITLE
Lab 4 - Unable to build project

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#74]
#### Step: 00

Description of issue
In the "testing" exercise near the end of this lab, after completing all of the steps perfectly, I cannot "build" and get the following error: 
![image](https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/assets/114931569/40a5ac8d-baf9-47d2-b4e3-ba78de97eee2)

I have tried a new model and new project. If I use the ApplicationSuite package (shown below) then I cannot **build**

![image](https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/assets/114931569/cd2881c8-6463-4a83-afc9-821ad59b0c39)

and if I remove this package I cannot carry out the steps in task 1:

![image](https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/assets/114931569/63de3827-efdc-4bf2-9fe2-2fce4bb1195a)

Any ideas? Thank you.

**Comment by janeteblake** [comment]
Thank you for your feedback, we appreciate it! We are investigating now.

**Comment by janeteblake** [comment]
Hello Lewis, we did not encounter the error. 

- Can you please send us a screenshot of your solution explorer like below?
- We are suspecting that the initial steps (3-11 or 13-18) are confusing and need a rewrite to make it clearer. That may be where it went wrong. 
- You cannot check too many boxes in referenced packages. It won't hurt.
Thank you, we await the screenshot!
Janet
![image](https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/assets/54034556/53bd6cb2-806a-4f0a-b655-4326ea4fed2b)

**Comment by LewisGoDeploy** [comment]
Thanks for getting back to me. My solution appears to be the exact same: 

![image](https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/assets/114931569/9be1263c-3298-4139-a463-2e20dff7d7c8)

**Comment by janeteblake** [comment]
Thank you for your response. I see you have prior labs there. Please tell me if you have done the labs in that machine, or imported them from our resources, and we'll recreate exactly.

**Comment by LewisGoDeploy** [comment]
The other labs were all completed according to the prior modules of this guide. I can try to do lab 4 without the others, however this wouldn't represent a real situation as students will always complete the first 3 before doing 4 - unless instructed to delete the rest.

**Comment by janeteblake** [comment]
Understood. I'm just trying to recreate _exactly_, since it works for me.

**Comment by LewisGoDeploy** [comment]
Hi again - does lab 4 work for you if you also do the first 3 labs prior? Not sure if this could be affecting it.

**Comment by LewisGoDeploy** [comment]
Is there any update on this?

**Comment by janeteblake** [comment]
Apologies that we don't have a definitive answer yet. We've had resource issues. 
Quick question - you previously said that labs 1, 2, and 3 had been done in that environment. Does that include the optional portions of Lab 1?
Thank you!

**Comment by LewisGoDeploy** [comment]
Yes I would have completed everything up until then

**Comment by janeteblake** [comment]
Lewis - still trying to recreate.

**Comment by janeteblake** [comment]
I think I see what happened, since I almost did the same myself.

In Exercise 2, Task 2, Step 6, it says to Right click on the Relations node of the **data entity**. If, instead, one were to right click on the relations node of the **table,** we would get that error that you saw. 

Can you please take a look and see if you think this is plausibly the error you encountered? If so, I will clarify the instructions so others don't get bitten - it's a super-subtle thing. 

Thank you!

**Comment by janeteblake** [comment]
Closing since we believe we have identified the source of the confusion. No correction / lab update needed.
