### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer#8]
Lab 05:

Hello Team,

first thank you for getting updates added to the instructions.   I have created a pull request: https://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer/pull/7 

In lab 5, there are a few areas where numbers do not have a space between the . and the word, causing issues in markdown rendering. I've also adjusted the html elements to fenced codeblocks ```.  

Would it be possible to have this merged upon your approval please?   Thank you for your time!

**Comment by mreherefortea** [comment]
Thanks team/Janet! Closing this issue out; greatly appreciate it. :)

**Comment by janeteblake** [comment]
Thanks for your contributions!
